/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package task_one;

/**
 *
 * @author ibrahim
 */
public class NewJFrame extends javax.swing.JFrame {
    
    int number_of_likes = 0; // this var calculates numbr of likes.
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        customizeView();
    }
    private void customizeView(){
        setTitle("Java course");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LikeButton = new javax.swing.JButton();
        DisLikeButton = new javax.swing.JButton();
        NumberOfLikes = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LikeButton.setText("Like");
        LikeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LikeButtonActionPerformed(evt);
            }
        });

        DisLikeButton.setText("Dislike");
        DisLikeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisLikeButtonActionPerformed(evt);
            }
        });

        NumberOfLikes.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addComponent(LikeButton)
                .addGap(83, 83, 83)
                .addComponent(DisLikeButton)
                .addGap(41, 41, 41)
                .addComponent(NumberOfLikes, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LikeButton)
                    .addComponent(DisLikeButton)
                    .addComponent(NumberOfLikes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/*
    I modified the code in the next lines
    */
    private void LikeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LikeButtonActionPerformed
        number_of_likes ++;
        if(number_of_likes<0)
            number_of_likes=0;
        NumberOfLikes.setText(""+number_of_likes);
    }//GEN-LAST:event_LikeButtonActionPerformed

    private void DisLikeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisLikeButtonActionPerformed
        number_of_likes--;
        if(number_of_likes<0)
            number_of_likes=0;
        NumberOfLikes.setText(""+number_of_likes);
    }//GEN-LAST:event_DisLikeButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DisLikeButton;
    private javax.swing.JButton LikeButton;
    private javax.swing.JLabel NumberOfLikes;
    // End of variables declaration//GEN-END:variables
}
